sudo: required
services:
  - docker

 before_install:
  - docker build -t gymdocker9903/docker-react -f Dockerfile.dev . 

 script:
  - docker run gymdocker9903/docker-react npm run test -- --coverage